services:
  - type: web
    name: jaime-merino-enhanced-bot
    runtime: python3
    plan: free
    buildCommand: |
      echo "🚀 Building Jaime Merino Enhanced Trading Bot"
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install -r requirements.txt
      echo "✅ Build completed successfully"
    startCommand: python enhanced_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: jaime-merino-enhanced-bot
          property: port
      - key: SECRET_KEY
        generateValue: true
      - key: BINANCE_API_KEY
        value: ""
      - key: BINANCE_SECRET_KEY
        value: ""
    healthCheckPath: /health
    disk:
      name: data
      mountPath: /data
      sizeGB: 1