services:
  - type: web
    name: jaime-merino-trading-bot
    runtime: python3
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: FLASK_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: jaime-merino-trading-bot
          property: port
    healthCheckPath: /
    disk:
      name: data
      mountPath: /data
      sizeGB: 1